### ISSUE TITLE
Fix model name parsing

### ISSUE THREAD

**Issue by lizmorr** [abmagil/haystack#16]
Using `ARGV` in `SearcherGenerator#modelnames` breaks the ability to pass the generator any options (arguments are in the ARGV array and are then treated as model names.)

Using Rails::Generators::NamedBased (as we are currently) gives the ability to use a `name` variable to access. However, the implication of NamedBase is that there is a single Name we are passing the Generator, and we want the ability to pass multiple model names, so we probably want to go with just Rails::Generators::Base.

**Comment by abmagil** [comment]
Fixed by https://github.com/abmagil/haystack/commit/490babe2d20c2d76e5abf5308cbaaec34f954712
